/* Automation Studio generated header file */
/* Do not edit ! */

#ifndef _LIBRARIES_20230315120928_
#define _LIBRARIES_20230315120928_

__asm__(".section \".plc\"");

/* Used IEC files */
__asm__(".ascii \"iecfile \\\"Logical/GlobalVariables/Loading/Ldg_Funct/Types.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/GlobalVariables/Loading/Ldg_Funct/Constants.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/GlobalVariables/Loading/Ldg_Funct/Ldg_Funct.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/standard/standard.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/runtime/runtime.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/runtime/runtime.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/runtime/runtime.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/FileIO/FileIO.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/FileIO/FileIO.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/FileIO/FileIO.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Ethernet/Ethernet.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Ethernet/Ethernet.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Ethernet/Ethernet.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/dvframe/dvframe.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/dvframe/dvframe.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/dvframe/dvframe.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/DataObj/DataObj.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/DataObj/DataObj.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/DataObj/DataObj.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/OPERATOR/operator.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsTime/astime.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsTime/astime.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsTime/astime.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsString/asstring.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsCANopen/AsCANopen.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsCANopen/AsCANopen.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/SupLib4/SupLib4.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/sys_lib/sys_lib.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/sys_lib/sys_lib.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/sys_lib/sys_lib.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsTCP/AsTCP.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsTCP/AsTCP.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsTCP/AsTCP.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/KGstring/KGstring.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/CAN_Lib/CAN_Lib.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/CAN_Lib/CAN_Lib.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/CAN_Lib/CAN_Lib.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Visapi/Visapi.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Visapi/Visapi.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Visapi/Visapi.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsARCfg/AsARCfg.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsARCfg/AsARCfg.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsARCfg/AsARCfg.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsETH/AsETH.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsETH/AsETH.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsETH/AsETH.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsDb/AsDb.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsDb/AsDb.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsDb/AsDb.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/brsystem/brsystem.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/brsystem/brsystem.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsUSB/AsUSB.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsUSB/AsUSB.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsUSB/AsUSB.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/WETCAN2/WETCAN2.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/WETCAN2/WETCAN2.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/WETCAN2/WETCAN2.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsMem/AsMem.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsMem/AsMem.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsArLog/AsArLog.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsArLog/AsArLog.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsArLog/AsArLog.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsBrWStr/AsBrWStr.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsBrWStr/AsBrWStr.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsUDP/AsUDP.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsUDP/AsUDP.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsUDP/AsUDP.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsIODiag/AsIODiag.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsIODiag/AsIODiag.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsIODiag/AsIODiag.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsBrStr/AsBrStr.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsIecCon/AsIecCon.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/IecCheck/IecCheck.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsXml/AsXml.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsXml/AsXml.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsXml/AsXml.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsPciStr/AsPciStr.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsPciStr/AsPciStr.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsPciStr/AsPciStr.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsIOAcc/AsIOAcc.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsIOAcc/AsIOAcc.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsIOAcc/AsIOAcc.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsBrMath/AsBrMath.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsBrMath/AsBrMath.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsBrMath/AsBrMath.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/MpServer/Types.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/MpServer/Constants.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/MpServer/MpServer.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Data_BackUp/DataBackUp/DataBackUp.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Data_BackUp/DataBackUp/DataBackUp.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Data_BackUp/DataBackUp/DataBackUp.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Robo_Drive_Control/FC302/FC302.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Robo_Drive_Control/FC302/FC302.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Robo_Drive_Control/FC302/FC302.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/KanLink_A19/KGFramework/Pkg_KGStandard/KGstdLib/KG_Cmd.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/KanLink_A19/KGFramework/Pkg_KGStandard/KGstdLib/Stat.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/KanLink_A19/KGFramework/Pkg_KGStandard/KGstdLib/KGstdLib.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/KanLink_A19/KGFramework/Pkg_KGStandard/KGstdLib/kgMachineState.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/KanLink_A19/KGFramework/Pkg_KGStandard/KGstdLib/kgMachinetyp.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/KanLink_A19/KGFramework/Pkg_KGStandard/KGstdLib/KG_Cmd.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/KanLink_A19/KGFramework/Pkg_KGStandard/KGstdLib/KGstdLib.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/KanLink_A19/KGFramework/Pkg_KGStandard/KGstdLib/kgMachineState.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/KanLink_A19/KGFramework/Pkg_KGStandard/KGstdLib/KGstdLib.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/KanLink_A19/KGFramework/Pkg_mnMsg/KGlibMsg/KGlibMsg.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/KanLink_A19/KGFramework/Pkg_mnMsg/KGlibMsg/KGlibMsg.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/KanLink_A19/KGFramework/Pkg_mnMsg/KGlibMsg/KGlibMsg.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/KanLink_A19/KGFramework/Pkg_mnParam/mnParamLib/mnParamLib.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/KanLink_A19/KGFramework/Pkg_mnParam/mnParamLib/mnParamLib.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/KanLink_A19/KGFramework/Pkg_mnParam/mnParamLib/mnParamLib.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/KanLink_A19/KGFramework/Pkg_hlKanLink/KanLinkLib/CmdBTxfer.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/KanLink_A19/KGFramework/Pkg_hlKanLink/KanLinkLib/CmdBI.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/KanLink_A19/KGFramework/Pkg_hlKanLink/KanLinkLib/CmdSilo.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/KanLink_A19/KGFramework/Pkg_hlKanLink/KanLinkLib/KLInterface.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/KanLink_A19/KGFramework/Pkg_hlKanLink/KanLinkLib/KanLinkLib.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/KanLink_A19/KGFramework/Pkg_hlKanLink/KanLinkLib/KanLinkLib.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/KanLink_A19/KGFramework/Pkg_hlKanLink/KanLinkLib/KanLinkLib.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/KanLink_A19/KGFrameworkShare/Pkg_hlKanLinkUser/KL_UserLib/Batch.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/KanLink_A19/KGFrameworkShare/Pkg_hlKanLinkUser/KL_UserLib/KL_UserLib.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/KanLink_A19/KGFrameworkShare/Pkg_hlKanLinkUser/KL_UserLib/KL_UserLib.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/KanLink_A19/KGFrameworkShare/Pkg_hlKanLinkUser/KL_UserLib/KL_UserLib.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/KanLink_A19/KGFrameworkShare/Pkg_hlKanLinkUser/KL_UserLib/CmdWetExt.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/KanLink_A19/KGFrameworkShare/Pkg_mnTestUser/libTestUse/libTest.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/KanLink_A19/KGFrameworkShare/Pkg_mnTestUser/libTestUse/libTestUse.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/KanLink_A19/KGFrameworkShare/Pkg_mnTestUser/libTestUse/libTest.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/KanLink_A19/KGFrameworkShare/Pkg_mnTestUser/libTestUse/libTestUse.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/KanLink_A19/KGFrameworkShare/Pkg_mnTestUser/libTestUse/libTestUse.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Displays/DispLib/DispLib.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Displays/DispLib/DispLib.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Displays/DispLib/DispLib.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/SQL/zzSQL_Lib/zzSQL_Lib.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/SQL/zzSQL_Lib/zzSQL_Lib.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/SQL/zzSQL_Lib/Constants.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/SQL/zzSQL_Lib/zzSQL_Lib.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/OPCuA/OPCuA/Constants.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/OPCuA/OPCuA/OPCuA.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/OPCuA/OPCuA/OPCuA.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Barcode_Readers/Code_Lib/Code_Lib.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Barcode_Readers/Code_Lib/Code_Lib.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Barcode_Readers/Code_Lib/ReaderColourConsts.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Barcode_Readers/Code_Lib/BarCodeCommands.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Barcode_Readers/Code_Lib/Code_Lib.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/http_Lib/AsHttp/AsHttp.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/http_Lib/AsHttp/AsHttp.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/http_Lib/AsHttp/AsHttp.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/http_Lib/KanHttp/Types.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/http_Lib/KanHttp/Constants.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/http_Lib/KanHttp/KanHttp.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/CustomLib/SUP/Types.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/CustomLib/SUP/Constants.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/CustomLib/SUP/SUP.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/File_System/FileMgr/Types.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/File_System/FileMgr/Constants.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/File_System/FileMgr/FileMgr.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Safety/AsSafety/AsSafety.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Safety/AsSafety/AsSafety.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Safety/AsSafety/AsSafety.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/HoistLibrary/MTTypes/MTTypes.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/HoistLibrary/MTTypes/MTTypes.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/HoistLibrary/MTTypes/MTTypes.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/HoistLibrary/MTBasics/MTBasics.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/HoistLibrary/MTBasics/MTBasics.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/HoistLibrary/MTBasics/MTBasics.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/ABB_EPL/AsEPL/AsEPL.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/ABB_EPL/AsEPL/AsEPL.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/ABB_EPL/AsEPL/AsEPL.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/ABB_EPL/ABB_EPL/ABB_EPL.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/ABB_EPL/ABB_EPL/Config.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/ABB_EPL/ABB_EPL/Constants.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/ABB_EPL/ABB_EPL/ABB_EPL.fun\\\" scope \\\"global\\\"\\n\"");

/* Exported library functions and function blocks */
#ifdef _LDG_FUNCT_EXPORT
	__asm__(".ascii \"plcexport \\\"LDG_GetBagFromStation\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LDG_GetStationFromBag\\\" FUN\\n\"");
#endif
#ifdef _STANDARD_EXPORT
	__asm__(".ascii \"plcexport \\\"RF_TRIG\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CTUD\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CTD\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CTU\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"F_TRIG\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"R_TRIG\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"SR\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"RS\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"SEMA\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"TON\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"TOF\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"TP\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"TON_10ms\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"TOF_10ms\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"TP_10ms\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"LEN\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LEFT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"RIGHT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"MID\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"CONCAT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INSERT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DELETE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REPLACE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"FIND\\\" FUN\\n\"");
#endif
#ifdef _RUNTIME_EXPORT
	__asm__(".ascii \"plcexport \\\"r_trig\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"f_trig\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"rf_trig\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"GetTime\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SFCActionControl\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"SFCAC2\\\" FUB\\n\"");
#endif
#ifdef _FILEIO_EXPORT
	__asm__(".ascii \"plcexport \\\"FileCreate\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"FileOpen\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"FileClose\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"FileRead\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"FileReadEx\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"FileWrite\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"FileWriteEx\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"FileRename\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"FileCopy\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"FileDelete\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"FileInfo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"FileTruncate\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DirCreate\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DirOpen\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DirClose\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DirRead\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DirReadEx\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DirInfo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DirRename\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DirCopy\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DirDelete\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DirDeleteEx\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"SetAttributes\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"GetAttributes\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DevMemInfo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DevLink\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DevUnlink\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"GetVolumeLabel\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"GetVolumeSerialNo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"FileIoGetSysError\\\" FUN\\n\"");
#endif
#ifdef _ETHERNET_EXPORT
	__asm__(".ascii \"plcexport \\\"ETHinfo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"SMTPxsendmail\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"ETHxinfo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"TCPclose\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"TCPrecv\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"TCPsend\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"TCPclient\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"TCPserv\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"ICMPping\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"SMTPsendmail\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"UDPclose\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"UDPopen\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"UDPrecv\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"UDPsend\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"ETHnode\\\" FUB\\n\"");
#endif
#ifdef _DVFRAME_EXPORT
	__asm__(".ascii \"plcexport \\\"FRM_mode\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"FRM_ctrl\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"FRM_robuf\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"FRM_gbuf\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"FRM_rbuf\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"FRM_close\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"FRM_write\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"FRM_read\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"FRM_xopen\\\" FUB\\n\"");
#endif
#ifdef _DATAOBJ_EXPORT
	__asm__(".ascii \"plcexport \\\"DatObjCreate\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DatObjWrite\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DatObjRead\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DatObjDelete\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DatObjMove\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DatObjCopy\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DatObjInfo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DatObjChangeDate\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DatObjAttach\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DatObjDetach\\\" FUB\\n\"");
#endif
#ifdef _OPERATOR_EXPORT
	__asm__(".ascii \"plcexport \\\"SIZEOF\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ADR\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SHR\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ROR\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ROL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SHL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"AND\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"XOR\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"OR\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"NOT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ADD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"MUL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SUB\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DIV\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"MOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"MOVE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"MAX\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"MIN\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LIMIT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SEL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"MUX\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"GE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"EQ\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"GT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"NE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ABS\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SQRT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LN\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LOG\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"EXP\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SIN\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"COS\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TAN\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ASIN\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ACOS\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ATAN\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"EXPT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TRUNC\\\" FUN\\n\"");
#endif
#ifdef _ASTIME_EXPORT
	__asm__(".ascii \"plcexport \\\"DTExSetTime\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DTSetTime\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DTGetTime\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"clock_ms\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UtcDTGetTime\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"UtcDTSetTime\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"UtcDTExSetTime\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DTStructureGetTime\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DTStructureSetTime\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DTStructureExSetTime\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"UtcDTStructureGetTime\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"UtcDTStructureSetTime\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"UtcDTStructureExSetTime\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"UtcDT_TO_LocalDTStructure\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"LocalDT_TO_UtcDTStructure\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"UtcDTStructure_TO_LocalDT\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"LocalDTStructure_TO_UtcDT\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"ascTIMEStructure\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ascDTStructure\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ascTIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ascDT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIMEStructure_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIME_TO_TIMEStructure\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DTStructure_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DT_TO_DTStructure\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DiffT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DiffDT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TimeDeviceGetInfo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DstGetInfo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DstGetInfoDT\\\" FUB\\n\"");
#endif
#ifdef _ASSTRING_EXPORT
	__asm__(".ascii \"plcexport \\\"ftoa\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"atof\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"itoa\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"atoi\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"memset\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"memcpy\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"memmove\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"memcmp\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"strcat\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"strlen\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"strcpy\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"strcmp\\\" FUN\\n\"");
#endif
#ifdef _ASCANOPEN_EXPORT
	__asm__(".ascii \"plcexport \\\"CANopenEnableCyclicSync\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CANopenGetLocalNodeID\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CANopenGetKernelState\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CANopenRegisterCOBID\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CANopenPDORead8\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CANopenPDOWrite8\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CANopenSDORead8\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CANopenSDOWrite8\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CANopenGetState\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CANopenNMT\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CANopenRecvEmcyDev\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CANopenRecvEmcy\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CANopenWriteEmcy\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CANopenRecvBootupDev\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CANopenRecvBootup\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CANopenSendSync\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CANopenSDOReadData\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CANopenSDOWriteData\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CANopenSetSDOTimeout\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"CANopenLayer2Read8\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CANopenGetSlaveState\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CANopenActivateSlaveMonitoring\\\" FUB\\n\"");
#endif
#ifdef _SUPLIB4_EXPORT
	__asm__(".ascii \"plcexport \\\"stUINT_ASC\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DIS4\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"stUNI5\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"stASC_UINT\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"BCD_BIN_OUTPUT\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"BIN_TO_BCD\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"stUNI4\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"BIT_ENCODE\\\" FUB\\n\"");
#endif
#ifdef _SYS_LIB_EXPORT
	__asm__(".ascii \"plcexport \\\"Byte2Bit\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"Bit2Byte\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"KEY_read\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"KEY_enadis\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DA_fix\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DA_info\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DA_copy\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DA_store\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DA_burn\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DA_delete\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DA_ident\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DA_read\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DA_write\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DA_create\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DIS_clr\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DIS_chr\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DIS_str\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ERRxfatal\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ERR_read\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ERRxread\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ERR_fatal\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ERR_warning\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ERRxwarning\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SM_release\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SM_attach\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SM_delete\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SM_ident\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SM_create\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIM_ticks\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIM_musec\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SW_settime\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SW_gettime\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"RTC_settime\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"RTC_gettime\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TMP_free\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TMP_alloc\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"MEM_free\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"MEM_alloc\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"AVT_info\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"AVT_release\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"AVT_attach\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"AVT_ident\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"AVT_cancel\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"AVT_create\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UT_sleep\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UT_exit\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UT_freemsg\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UT_recmsg\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UT_sendmsg\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UT_resume\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UT_suspend\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UT_ident\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ST_name\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ST_info\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ST_allsuspend\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ST_tmp_resume\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ST_tmp_suspend\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ST_resume\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ST_suspend\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ST_ident\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"FORCE_info\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"MO_ver\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"MO_list\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"MO_info\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"SYS_battery\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SYSreset\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SYSxinfo\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SYS_info\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"PV_xlist\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"PV_ninfo\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"PV_item\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"PV_ident\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"PV_list\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"PV_info\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"PV_xgetval\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"PV_xsetval\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"PV_xgetadr\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"PV_getadr\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"PV_getval\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"PV_setval\\\" FUN\\n\"");
#endif
#ifdef _ASTCP_EXPORT
	__asm__(".ascii \"plcexport \\\"TcpOpen\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"TcpServer\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"TcpClient\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"TcpClose\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"TcpSend\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"TcpRecv\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"TcpIoctl\\\" FUB\\n\"");
#endif
#ifdef _KGSTRING_EXPORT
	__asm__(".ascii \"plcexport \\\"NetMaskToStr\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"strToNetMask\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"udiToString\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"setStrLen\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"uiToString\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"dtToString\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"secToMMSS\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"secToHHMM\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"dateToString\\\" FUB\\n\"");
#endif
#ifdef _CAN_LIB_EXPORT
	__asm__(".ascii \"plcexport \\\"CANinfo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CANMulQueue\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CANxMulQueue\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CANMulOpen\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CANMulrd\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CANTime\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CANquwr\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"SetNdNr\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"GetNdNr\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CMSmain\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CMSinit\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CMSdlreq\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CMSdlcon\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CANxnode\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CANwrite\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CANupd\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CANngp\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CANrwtab\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CANrtr\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CANread\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CANrd\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CANxrd\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CANqueue\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CANopen\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CANnode\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CANgetid\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CANexcep\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CANdftab\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CANbtreg\\\" FUB\\n\"");
#endif
#ifdef _VISAPI_EXPORT
	__asm__(".ascii \"plcexport \\\"VA_Attach\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_BlitBitmap\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_Configure\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_CopyScreenRect\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_DelAlarmHistory\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_GetActiveAlarmCount\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_GetAlarmCount\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_Detach\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_DrawBitmap\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_Ellipse\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_ExchangeFont\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_ExtractKeyMatrix\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_FreeBitmap\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_GetActAlarmList\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_GetAlCurPos\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_GetAlarmList\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_GetBrightness\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_GetCalStatus\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_GetContrast\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_GetDisplayInfo\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_GetExAlarmList\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_GetKeyMatrix\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_GetPaletteColor\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_GetPanelStatus\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_GetTextByTextGroup\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_GetTouchAction\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_LangIsAvailable\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_Line\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_LoadBitmap\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_NGetAlCurPos\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_NGetCalStatus\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_NGetContrast\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_NGetPaletteColor\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_Quit\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_QuitAlarms\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_Rect\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_Redraw\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_Saccess\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_SaveSettings\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_SetBacklight\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_SetBrightness\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_SetClipRegion\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_SetContrast\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_SetPaletteColor\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_SetUserParam\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_Setup\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_SetupX\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_Shutdown\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_Srelease\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_StartProject\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_StartVisuByName\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_StartTouchCal\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_StopProject\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_Textout\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_TimeSynchronize\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_wcAlarmGetList\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_wcGetActAlarmList\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_wcGetExAlarmList\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_wcGetTextByTextGroup\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_wcTextout\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_GetActualLang\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_ClearTouchEventBuffer\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_RegisterClient\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_StartProcess\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_TerminateProcess\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_GetProcessExitCode\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_SetProcessZOrder\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_SetVisualizationZOrder\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_RunJScript\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_SetBeep\\\" FUN\\n\"");
#endif
#ifdef _ASARCFG_EXPORT
	__asm__(".ascii \"plcexport \\\"CfgGetInaNode\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgSetInaNode\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgGetIPAddr\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgSetIPAddr\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgGetSubnetMask\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgSetSubnetMask\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgGetDefaultGateway\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgSetDefaultGateway\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgGetBroadcastAddr\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgSetBroadcastAddr\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgGetEthBaudrate\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgSetEthBaudrate\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgGetEthConfigMode\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgSetEthConfigMode\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgGetHostName\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgSetHostName\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgGetMacAddr\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgSetFTPServer\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgGetTimeOffset\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgSetTimeOffset\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgSetSntpServer\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgSetSntpClient\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgGetSntpcData\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgGetSntpsData\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgGetTimeZone\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgSetTimeZone\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgGetTimeZoneInfo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgGetTimeZoneEntry\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgGetDst\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgSetDst\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgGetCIFSDomain\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgSetCIFSDomain\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgGetCIFSDefaultuser\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgSetCIFSDefaultuser\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgSetDhcpServer\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgSetDhcpsData\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgGetDhcpsData\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgSetSdmStatus\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgGetSdmStatus\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgClearNV\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgSetSdmColor\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgGetSdmColor\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgGetSdmCustomData1\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgSetSdmCustomData1\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgGetSdmCustomData2\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgSetSdmCustomData2\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgGetWebMimeType\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgSetWebMimeType\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgGetWebServerPort\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgGetWebServerDevice\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgGetWebAspGoform\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgSetWebAspGoform\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgGetWebServerStatus\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgSetWebServerStatus\\\" FUB\\n\"");
#endif
#ifdef _ASETH_EXPORT
	__asm__(".ascii \"plcexport \\\"EthStat\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"ethInetAton\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ethInetNtoa\\\" FUN\\n\"");
#endif
#ifdef _ASDB_EXPORT
	__asm__(".ascii \"plcexport \\\"dbConnect\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"dbConnectEnc\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"dbExecuteSql\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"dbGetAffectedRows\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"dbGetColumnCount\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"dbFetchNextRow\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"dbGetData\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"dbDisconnect\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"dbGetInfo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"dbGetErrorMessage\\\" FUB\\n\"");
#endif
#ifdef _BRSYSTEM_EXPORT
	__asm__(".ascii \"plcexport \\\"MEMInfo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MEMxInfo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"SysInfo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"RTInfo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"TARGETInfo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"HWInfo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"SysconfInfo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"SysconfSet\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"BatteryInfo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"EXCInfo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"ZYKVLenable\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"PMemGet\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"PMemPut\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"PMemSize\\\" FUB\\n\"");
#endif
#ifdef _ASUSB_EXPORT
	__asm__(".ascii \"plcexport \\\"UsbNodeListGet\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"UsbNodeGet\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"UsbDescriptorGet\\\" FUB\\n\"");
#endif
#ifdef _WETCAN2_EXPORT
	__asm__(".ascii \"plcexport \\\"_GetNumberOfCan1Tels\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"_SetCAN2COBTypeToCAN2Type\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"_SetCAN2TypeToCAN1Type\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"_GetCANIDFromObjNr\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"_GetPVSize\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"_SetCAN1TypeToByteArray\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"_Seti386CAN2TypeToCAN1Type\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"_ConvertDataToi386\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CAN2RW\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CAN2Init\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"_version\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"_swapUINT\\\" FUN\\n\"");
#endif
#ifdef _ASMEM_EXPORT
	__asm__(".ascii \"plcexport \\\"AsMemPartCreate\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"AsMemPartDestroy\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"AsMemPartAlloc\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"AsMemPartAllocClear\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"AsMemPartRealloc\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"AsMemPartFree\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"AsMemPartInfo\\\" FUB\\n\"");
#endif
#ifdef _ASARLOG_EXPORT
	__asm__(".ascii \"plcexport \\\"AsArLogCreate\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"AsArLogDelete\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"AsArLogWrite\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"AsArLogRead\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"AsArLogClear\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"AsArLogGetInfo\\\" FUB\\n\"");
#endif
#ifdef _ASBRWSTR_EXPORT
	__asm__(".ascii \"plcexport \\\"brwcsconv\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brwcsncpy\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brwcsncat\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brwcscat\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brwcscmp\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brwcslen\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brwcsset\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brwcsncmp\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brwcscpy\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brwcsrchr\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brwcschr\\\" FUN\\n\"");
#endif
#ifdef _ASUDP_EXPORT
	__asm__(".ascii \"plcexport \\\"UdpOpen\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"UdpClose\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"UdpConnect\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"UdpDisconnect\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"UdpSend\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"UdpRecv\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"UdpIoctl\\\" FUB\\n\"");
#endif
#ifdef _ASIODIAG_EXPORT
	__asm__(".ascii \"plcexport \\\"DiagCreateInfo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DiagDisposeInfo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DiagGetNumInfo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DiagGetStrInfo\\\" FUB\\n\"");
#endif
#ifdef _ASBRSTR_EXPORT
	__asm__(".ascii \"plcexport \\\"brsftoa\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brsatof\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brsitoa\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brsatoi\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brsmemset\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brsmemcpy\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brsmemmove\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brsmemcmp\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brsstrcat\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brsstrlen\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brsstrcpy\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brsstrcmp\\\" FUN\\n\"");
#endif
#ifdef _ASIECCON_EXPORT
	__asm__(".ascii \"plcexport \\\"swapDT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"swapTIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"swapDATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"swapTOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"swapREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"swapLREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"swapUDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"swapDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"swapUINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"swapINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"swapWORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"swapDWORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"N_TO_HDT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"N_TO_HTIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"N_TO_HDATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"N_TO_HTOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"N_TO_HREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"N_TO_HLREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"N_TO_HUDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"N_TO_HDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"N_TO_HUINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"N_TO_HINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"H_TO_NDT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"H_TO_NTIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"H_TO_NDATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"H_TO_NTOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"H_TO_NREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"H_TO_NLREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"H_TO_NUDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"H_TO_NDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"H_TO_NUINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"H_TO_NINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BOOL_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BOOL_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BOOL_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BOOL_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BOOL_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BOOL_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BOOL_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BOOL_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BOOL_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BOOL_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BOOL_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BOOL_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BOOL_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BOOL_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BOOL_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BOOL_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BOOL_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BYTE_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BYTE_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BYTE_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BYTE_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BYTE_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BYTE_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BYTE_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BYTE_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BYTE_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BYTE_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BYTE_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BYTE_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BYTE_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BYTE_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BYTE_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BYTE_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BYTE_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WORD_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WORD_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WORD_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WORD_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WORD_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WORD_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WORD_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WORD_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WORD_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WORD_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WORD_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WORD_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WORD_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WORD_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WORD_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WORD_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WORD_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DWORD_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DWORD_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DWORD_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DWORD_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DWORD_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DWORD_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DWORD_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DWORD_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DWORD_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DWORD_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DWORD_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DWORD_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DWORD_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DWORD_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DWORD_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DWORD_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DWORD_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SINT_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SINT_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SINT_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SINT_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SINT_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SINT_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SINT_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SINT_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SINT_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SINT_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SINT_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SINT_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SINT_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SINT_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SINT_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SINT_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SINT_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INT_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INT_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INT_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INT_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INT_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INT_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INT_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INT_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INT_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INT_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INT_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INT_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INT_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INT_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INT_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INT_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INT_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DINT_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DINT_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DINT_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DINT_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DINT_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DINT_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DINT_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DINT_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DINT_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DINT_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DINT_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DINT_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DINT_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DINT_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DINT_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DINT_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DINT_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"USINT_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"USINT_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"USINT_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"USINT_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"USINT_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"USINT_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"USINT_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"USINT_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"USINT_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"USINT_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"USINT_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"USINT_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"USINT_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"USINT_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"USINT_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"USINT_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"USINT_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UINT_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UINT_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UINT_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UINT_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UINT_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UINT_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UINT_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UINT_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UINT_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UINT_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UINT_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UINT_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UINT_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UINT_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UINT_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UINT_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UINT_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UDINT_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UDINT_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UDINT_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UDINT_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UDINT_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UDINT_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UDINT_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UDINT_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UDINT_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UDINT_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UDINT_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UDINT_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UDINT_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UDINT_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UDINT_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UDINT_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UDINT_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIME_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIME_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIME_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIME_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIME_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIME_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIME_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIME_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIME_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIME_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIME_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIME_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIME_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIME_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIME_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIME_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIME_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DT_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DT_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DT_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DT_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DT_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DT_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DT_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DT_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DT_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DT_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DT_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DT_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DT_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DT_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DT_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DT_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DT_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DATE_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DATE_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DATE_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DATE_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DATE_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DATE_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DATE_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DATE_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DATE_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DATE_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DATE_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DATE_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DATE_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DATE_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DATE_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DATE_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DATE_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TOD_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TOD_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TOD_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TOD_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TOD_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TOD_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TOD_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TOD_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TOD_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TOD_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TOD_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TOD_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TOD_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TOD_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TOD_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TOD_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TOD_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REAL_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REAL_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REAL_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REAL_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REAL_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REAL_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REAL_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REAL_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REAL_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REAL_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REAL_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REAL_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REAL_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REAL_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REAL_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REAL_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REAL_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LREAL_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LREAL_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LREAL_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LREAL_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LREAL_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LREAL_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LREAL_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LREAL_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LREAL_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LREAL_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LREAL_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LREAL_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LREAL_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LREAL_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LREAL_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LREAL_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LREAL_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"STRING_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"STRING_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"STRING_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"STRING_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"STRING_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"STRING_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"STRING_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"STRING_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"STRING_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"STRING_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"STRING_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"STRING_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"STRING_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"STRING_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"STRING_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"STRING_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"STRING_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WSTRING_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WSTRING_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WSTRING_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WSTRING_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WSTRING_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WSTRING_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WSTRING_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WSTRING_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WSTRING_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WSTRING_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WSTRING_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WSTRING_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WSTRING_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WSTRING_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WSTRING_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WSTRING_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WSTRING_TO_STRING\\\" FUN\\n\"");
#endif
#ifdef _IECCHECK_EXPORT
	__asm__(".ascii \"plcexport \\\"CheckDivDWord\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"CheckDivWord\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"CheckDivByte\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"CheckDivReal\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"CheckDivLReal\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"CheckBounds\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"CheckRange\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"CheckSignedSubrange\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"CheckUnsignedSubrange\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"CheckReadAccess\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"CheckWriteAccess\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"MakeEntry\\\" FUN\\n\"");
#endif
#ifdef _ASXML_EXPORT
	__asm__(".ascii \"plcexport \\\"xmlCreateMemoryReader\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"xmlCloseMemoryReader\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"xmlReadNextNode\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"xmlReadAttributeNr\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"xmlCreateMemoryWriter\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"xmlGetMemoryInfo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"xmlCloseMemoryWriter\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"xmlWriteStartDocument\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"xmlWriteStartDocEnc\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"xmlWriteEndDocument\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"xmlWriteStartElement\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"xmlWriteAttribute\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"xmlWriteElementText\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"xmlWriteElementTextEx\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"xmlWriteEndElement\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"xmlWriteComment\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"xmlWriteCommentEx\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"xmlWriteCData\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"xmlWritePI\\\" FUB\\n\"");
#endif
#ifdef _ASPCISTR_EXPORT
	__asm__(".ascii \"plcexport \\\"pciMemSet\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"pciMemCpy\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"pciMemMove\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"pciMemCmp\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"pciStrCat\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"pciStrCpy\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"pciStrCmp\\\" FUN\\n\"");
#endif
#ifdef _ASIOACC_EXPORT
	__asm__(".ascii \"plcexport \\\"AsIOAccRead\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"AsIOAccWrite\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"AsIOAccReadReg\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"AsIOAccWriteReg\\\" FUB\\n\"");
#endif
#ifdef _ASBRMATH_EXPORT
	__asm__(".ascii \"plcexport \\\"brmatan2\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brmceil\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brmcosh\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brmfloor\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brmfmod\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brmfrexp\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brmldexp\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brmmodf\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brmpow\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brmsinh\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brmtanh\\\" FUN\\n\"");
#endif
#ifdef _DATABACKUP_EXPORT
	__asm__(".ascii \"plcexport \\\"DataBackUp\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CopyToFileDevice\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"ReadFromFileDevice\\\" FUB\\n\"");
#endif
#ifdef _FC302_EXPORT
	__asm__(".ascii \"plcexport \\\"FC302_WriteParam\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"FC302_ReadSTW\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"FC302_WriteCTW\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"FC302_ReadParamTbl\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"FC302_ReadParam\\\" FUB\\n\"");
#endif
#ifdef _KGSTDLIB_EXPORT
	__asm__(".ascii \"plcexport \\\"kgGetEthPort\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"kgitoa_udint\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"kgatoi_udint\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"kgatoi_uint\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"kgNextBatchNoLong\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"kgGetMacAdress\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"kgGetBatchNoUnique\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"kgBatchNoToUDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"kgUSINT16toGUID\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"kgGUIDtoSTRING\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"kgLogLine\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"kgArLogWrite\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"kgRBinsert\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"kgRBread\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"kgRBloc\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"kgGUIDisZero\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"kgRBcreate\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"kgRBbulkloc\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"kgGetLineNumberW3\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"kgInitBatchNoLong\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"kgGetMachineAdressW3\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"kgCheckDo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"kgXOR\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"kgUnitconfREALtoDisplay\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"kgUnitconfDisplayToREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"kgGetProgdata\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"kgSignalLight\\\" FUN\\n\"");
#endif
#ifdef _KGLIBMSG_EXPORT
	__asm__(".ascii \"plcexport \\\"msgBinSearchCfgList\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"msgInsertMsgLine\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"msgBinSearchTxtLine\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"msgBinSearchHelpTxtLine\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"msgReplSubStr\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"msgNextChrPos\\\" FUB\\n\"");
#endif
#ifdef _MNPARAMLIB_EXPORT
	__asm__(".ascii \"plcexport \\\"mnParam_BinarySearchInNumeric\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"mnParam_CountLines\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"mnParam_GetCsvDat\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"mnParam_atodatetime\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"mnParam_GetNextSubstring\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"mnParam_GetContainerOfParamNum\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"GetArrayPV\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"mnParam_WritePVNum\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"mnParam_WritePVrNum\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"mnParam_GetContainerOfParamStrin\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"mnParam_WritePVString\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"mnParam_BinarySearchInString\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"mnParam_WriteCSV255_Mem\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"mnParam_WriteBOM_Mem\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"mnParam_WriteCSV254_Mem\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"mnParam_WriteNewline_Mem\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"mnParam_datetimetoa\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"mnParam_datetoa\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"mnParam_WriteCSV253_Mem\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"mnParam_WriteCSV252_Mem\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"mnParam_WriteCSV251_Mem\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"mnParam_WriteCSV10_Mem\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"mnParam_WriteCSV20_Mem\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"mnParam_WriteCSV80_Mem\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"mnParam_WriteCSV81_Mem\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"mnParam_WriteCSV90_Mem\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"mnParam_WriteCSV11_Mem\\\" FUB\\n\"");
#endif
#ifdef _KANLINKLIB_EXPORT
	__asm__(".ascii \"plcexport \\\"KanLink_FB\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"KLLib_ClientTimer\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"KLLib_GetPVAdr\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"KLLib_SendData\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"KLLib_ReadServerPara\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"KLLib_ReadClientPara\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"KLLib_InitCltPV\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"KLLib_Init\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"KL_BuildKey\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"KLLib_CfgClient\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"KLLib_CfgServer\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"KLLib_CreateStrucDef\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"KLLib_WriteStrucDefLine\\\" FUN\\n\"");
#endif
#ifdef _KL_USERLIB_EXPORT
	__asm__(".ascii \"plcexport \\\"KL_OnRecReq\\\" FUN\\n\"");
#endif
#ifdef _LIBTESTUSE_EXPORT
	__asm__(".ascii \"plcexport \\\"TestUser_SetMode\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"TestUser_RunTest\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"TestUser_StopTask\\\" FUN\\n\"");
#endif
#ifdef _DISPLIB_EXPORT
	__asm__(".ascii \"plcexport \\\"IP_Replace\\\" FUB\\n\"");
#endif
#ifdef _ZZSQL_LIB_EXPORT
	__asm__(".ascii \"plcexport \\\"SQL_Write\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"SQL_Read_Write\\\" FUB\\n\"");
#endif
#ifdef _OPCUA_EXPORT
	__asm__(".ascii \"plcexport \\\"OPCuA_DisplayEncode_Bin\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"OPCuA_DisplayEncode_String\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"OPCuA_BagEncode_Bin\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"OPCuA_DisplayDecode\\\" FUB\\n\"");
#endif
#ifdef _CODE_LIB_EXPORT
	__asm__(".ascii \"plcexport \\\"CloseAllOpenTCPIdents\\\" FUB\\n\"");
#endif
#ifdef _ASHTTP_EXPORT
	__asm__(".ascii \"plcexport \\\"httpService\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"httpClient\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"httpsService\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"httpsClient\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"httpUtf8ToString\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"httpStringToUtf8\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"httpUtf8ToWString\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"httpWStringToUtf8\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"httpDecodeBase64\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"httpEncodeBase64\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"httpEncodeUrl\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"httpDecodeUrl\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"httpGetParamUrl\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"httpSetParamUrl\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"httpSetBoundary\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"httpGetBoundary\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"httpSetMultipartMessage\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"httpGetMultipartMessage\\\" FUB\\n\"");
#endif
#ifdef _KANHTTP_EXPORT
	__asm__(".ascii \"plcexport \\\"httpGetParameter\\\" FUB\\n\"");
#endif
#ifdef _SUP_EXPORT
	__asm__(".ascii \"plcexport \\\"getWaitingLongest\\\" FUB\\n\"");
#endif
#ifdef _FILEMGR_EXPORT
	__asm__(".ascii \"plcexport \\\"fileReadWrite\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"fileToDatObj\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"fileToMem\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"FileCopyFromDev\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"WriteXMLFromStructure\\\" FUB\\n\"");
#endif
#ifdef _ASSAFETY_EXPORT
	__asm__(".ascii \"plcexport \\\"safeRemoteControl\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"safeDownloadApplication\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"safeDownloadData\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"safeConfigurationOnTarget\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"safeLibraryVersion\\\" FUN\\n\"");
#endif
#ifdef _MTBASICS_EXPORT
	__asm__(".ascii \"plcexport \\\"MTBasicsDT1\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MTBasicsDT2\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MTBasicsIntegrator\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MTBasicsLevelController\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MTBasicsLimiter\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MTBasicsOscillationTuning\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MTBasicsPFM\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MTBasicsPID\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MTBasicsPT1\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MTBasicsPT2\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MTBasicsPWM\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MTBasicsPWMSchedule\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MTBasicsStepTuning\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MTBasicsTimeDelay\\\" FUB\\n\"");
#endif
#ifdef _ASEPL_EXPORT
	__asm__(".ascii \"plcexport \\\"EplSDORead\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"EplSDOWrite\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"EplGetLocalNodeID\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"EplCreateObject\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"EplDeleteObject\\\" FUB\\n\"");
#endif
#ifdef _ABB_EPL_EXPORT
	__asm__(".ascii \"plcexport \\\"ABB_PackData\\\" FUB\\n\"");
#endif

__asm__(".previous");


#endif /* _LIBRARIES_20230315120928_ */

