
ACTION _setBeltTime: 
	
BeltAddTimeArray[1] := 4;
BeltAddTimeArray[2] := 4;
BeltAddTimeArray[3] := 4;
BeltAddTimeArray[4] := 4;
BeltAddTimeArray[5] := 3;
BeltAddTimeArray[6] := 3;
BeltAddTimeArray[7] := 3;
BeltAddTimeArray[8] := 3;
BeltAddTimeArray[9] := 2;
BeltAddTimeArray[10] := 2;
BeltAddTimeArray[11] := 2;
BeltAddTimeArray[12] := 2;
BeltAddTimeArray[13] := 1;
BeltAddTimeArray[14] := 1;
BeltAddTimeArray[15] := 1;
BeltAddTimeArray[16] := 1;
BeltAddTimeArray[17] := 0;
BeltAddTimeArray[18] := 0;
BeltAddTimeArray[19] := 0;
BeltAddTimeArray[20] := 0;
BeltAddTimeArray[42] := 5;
	
	
		
END_ACTION
