
ACTION _setBeltTime: 
	
BeltAddTimeArray[1] := 1;
BeltAddTimeArray[2] := 1;
BeltAddTimeArray[3] := 2;
BeltAddTimeArray[4] := 2;
BeltAddTimeArray[5] := 3;
BeltAddTimeArray[6] := 3;
BeltAddTimeArray[7] := 4;
BeltAddTimeArray[8] := 4;
BeltAddTimeArray[9] := 5;
BeltAddTimeArray[10] := 5;
BeltAddTimeArray[11] := 6;
BeltAddTimeArray[12] := 6;
BeltAddTimeArray[13] := 7;
BeltAddTimeArray[14] := 7;
BeltAddTimeArray[15] := 8;
BeltAddTimeArray[16] := 8;

	
	
		
END_ACTION
